//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public string Where1 { get; set; }
        public string Where2 { get; set; }
        public string What { get; set; }
        public int TypeDil { get; set; }
        public string TypePay { get; set; }
        public int id_user { get; set; }
    
        public virtual TypeDelivery TypeDelivery { get; set; }
        public virtual Userss Userss { get; set; }
    }
}
